<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="DESKTOP-K1R7T5H" failures="1" tests="4" name="tr_technologies.Tests.ErrorValidationsTest" time="13.988" errors="0" timestamp="2025-01-21T20:47:08 IST" skipped="2">
  <testcase classname="tr_technologies.Tests.ErrorValidationsTest" name="LoginErrorValidation" time="4.919">
    <skipped/>
  </testcase> <!-- LoginErrorValidation -->
  <system-out/>
  <testcase classname="tr_technologies.Tests.ErrorValidationsTest" name="LoginErrorValidation" time="2.683">
    <skipped/>
  </testcase> <!-- LoginErrorValidation -->
  <system-out/>
  <testcase classname="tr_technologies.Tests.ErrorValidationsTest" name="LoginErrorValidation" time="2.237">
    <failure message="expected [Incorrect email or password.] but found [Incorrect email password.]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [Incorrect email or password.] but found [Incorrect email password.]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEqualsImpl(Assert.java:140)
at org.testng.Assert.assertEquals(Assert.java:122)
at org.testng.Assert.assertEquals(Assert.java:629)
at org.testng.Assert.assertEquals(Assert.java:639)
at tr_technologies.Tests.ErrorValidationsTest.LoginErrorValidation(ErrorValidationsTest.java:22)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.retryFailed(TestInvoker.java:213)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:58)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.access$000(SuiteRunner.java:28)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:418)
at org.testng.internal.thread.ThreadUtil.lambda$execute$0(ThreadUtil.java:64)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1583)
]]>
    </failure>
  </testcase> <!-- LoginErrorValidation -->
  <system-out/>
  <testcase classname="tr_technologies.Tests.ErrorValidationsTest" name="ProductErrorValidation" time="4.149"/>
  <system-out/>
</testsuite> <!-- tr_technologies.Tests.ErrorValidationsTest -->
